import type { Metadata } from 'next'
import Image from 'next/image'
import localFont from 'next/font/local'
import './globals.css'

import HeroIllustration from '../../public/home-page-assets/Hero Illustration.png'
import HeroImage from '../../public/home-page-assets/hero-image.jpg'

import Footer from './components/Footer'
import Navbar from './components/Navbar'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

const latoRegular = localFont({
	src: './fonts/Lato-Regular.ttf',
	variable: '--font-lato-regular',
})

const latoBlack = localFont({
	src: './fonts/Lato-Black.ttf',
	variable: '--font-lato-black',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${latoRegular.variable} ${latoBlack.variable} antialiased flex flex-col min-h-screen overflow-x-hidden bg-[#420081]`}>
				{/* Hero section */}
				<div
					className="h-screen w-screen bg-no-repeat bg-cover"
					style={{ backgroundImage: `url(${HeroImage.src})` }}>
					{/* Navbar over hero image */}
					<Navbar />
          {/* Mozda dinamicka velicina citanjem visine navbara */}
          <div className="flex justify-start w-screen relative" style={{ height: 'calc(100% - 76.5px)' }}> 
            <h1 className="font-latoBlack text-9xl w-52 md:w-[948px] text-white ml-20">
              SPEND LESS, BUY MORE
            </h1>
            <Image
              src={HeroIllustration}
              alt="Hero Illustration"
              className="absolute w-auto right-0 bottom-0 h-3/5 mr-20"
            />
          </div>
				</div>
				{/* Main content */}
				<main className="flex-grow flex flex-col">{children}</main>
				{/* Footer */}
				<Footer />
			</body>
		</html>
	)
}
